### ISSUE TITLE
Add any of your project you want to share.

### ISSUE THREAD

**Issue by ron2111** [ron2111/Hacktoberfest2021_awesome-projects#1]
Make sure the folder's name is the same as the **project's name** & include a **readme file** with a brief about the project and its uses.

**Comment by ayushsoni1010** [comment]
Hey @ron2111 👋
I would like to work on this issue and want to add a project of frontend-mentor-challenges by frontmentor.io
Could you please assign me this issue under Hacktoberfest 2021

Thanks✨

**Comment by TechSpiritSS** [comment]
Hey @ron2111
I would like to add a C++ Project into this.
Its CLI Based Tic Tac Toe Game written by me from scratch.

**Comment by Rishavgupta12345** [comment]
bro i am adding tic tac toe project i wrote from scratch in kotlin language . please assign me

**Comment by TechSpiritSS** [comment]
You can add anything without asking for assign make sure to check the accouchement before making Pull Requests

**Comment by Ankush144** [comment]
hey do i need to create a new branch for every project ? or can i push in the main branch itself ?

**Comment by TechSpiritSS** [comment]
it's better to make new branch

**Comment by Upasana1216** [comment]
I would like to add sudoku solver in c++. Solved using backtracking. Please assign that to me

**Comment by TechSpiritSS** [comment]
you can send PR regarding that directly, check the announcements before making any PR

**Comment by ramyamahi** [comment]
Simple personal portfolio website added. Please check the PR #206

**Comment by 2201monesh** [comment]
Hey @ron2111 I have added a certificate generator in the Javascript folder can you give #281 a Hacktoberfest label.

**Comment by amanrk28** [comment]
Hi @ron2111 I've created a PR for a project I made in HTML Projects folder. Please check the PR #356

**Comment by MannyP31** [comment]
Hello @ron2111 , I've created a PR for a web crawler in python ( PR #370 ). Kindly go through that.

**Comment by amanrk28** [comment]
Hey @ron2111 I've created a PR for a Relaxer app in HTML projects folder( PR #371  ).
