### ISSUE TITLE
Make a new folder for **clones** 

### ISSUE THREAD

**Issue by ron2111** [ron2111/Hacktoberfest2021_awesome-projects#132]
Make a new folder in the repo named **"Stunning clones"** with a project_doc.md file for the descriptions of the projects to be added in the folder.

1. Initiate the project_doc.md file with instructions like: *Add all your clone projects here* 
2. Add the Youtube-clone project to this folder

**Comment by Manas1820** [comment]
Hey i can take this up

**Comment by Manas1820** [comment]
@ron2111 I have added the changes in my project PR only

**Comment by ItsRoy69** [comment]
Hey can I get assigned for this?

**Comment by TechSpiritSS** [comment]
it's open to all no need for assign @ItsRoy69
