### ISSUE TITLE
Important Announcement !!

### ISSUE THREAD

**Issue by ron2111** [ron2111/Hacktoberfest2021_awesome-projects#17]
### Discussed in https://github.com/ron2111/Hacktoberfest2021_awesome-projects/discussions/16

<div type='discussions-op-text'>

<sup>Originally posted by **ron2111** October  1, 2021</sup>
While raising a PR, make sure to update the project_doc available inside the specific techstack folder with the description of your project:

Heading: <h2>

And, add your names to the list of contributors in README.md too without deleting the template for adding it.</div>

**Comment by TechSpiritSS** [comment]
### ** New Update! **

# Do not edit the readme file
# Fetch Upstream before Pull Request to avoid merge conflicts
# Add your Project info in Project_doc.md file in the SAME PR
