### ISSUE TITLE
Digit Recognizer using KNN 

### ISSUE THREAD

**Issue by anubhav201241** [ron2111/Hacktoberfest2021_awesome-projects#170]
Hey, I want to contribute to your repository under Hacktoberfest'21
I want to add Digit Recognizer code using Knn Algorithm 

@ron2111 Please assign this issue to me

**Comment by ArkajyotiChakraborty** [comment]
Hey, i want to contribute on this, I'm a ML enthusiast and been working on and learning, hence can be helpful for learning purpose.

**Comment by anubhav201241** [comment]
> Hey, I want to contribute on this, I'm an ML enthusiast and been working on and learning, hence can be helpful for learning purpose.

same here bro 🙄🙂

**Comment by ron2111** [comment]
yup, you can add it

**Comment by anubhav201241** [comment]
dud @ron2111 why do you closed my issue I have to contribute to this repo why you had closed it
