### ISSUE TITLE
Share your amazing ML/Python projects

### ISSUE THREAD

**Issue by ron2111** [ron2111/Hacktoberfest2021_awesome-projects#2]
Add the projects under the respective **tech stack folder only** & raise genuine PRs.

**Comment by dbmohit** [comment]
can i work on this?

**Comment by Sravanthgithub** [comment]
Hey!! I wanna work on this issue, I am an ML enthusiast So, I will be adding some bunch of projects if you please let me take up this issue.

Thanks!!

**Comment by shubhamnag14** [comment]
I would like to contribute in this repo as well

**Comment by euhidaman** [comment]
Added Weather Scraping in Python #99

**Comment by rSrikesh** [comment]
I have added a ml project using two codes - one using sklearn libraries and other based on basic python classes
It is a single layer  perceptron model
Pls check it and merge it 
Thank You

**Comment by euhidaman** [comment]
> Added Weather Scraping in Python #99

Fixed my merge conflict.
It's been  7 hours.
Hopefully, my pull request get's merged now.
#99

**Comment by nehal6657** [comment]
Hey! I have added a project that converts faces into emojis of appropriate mood.
Hope you find it useful.
PR #200
