### ISSUE TITLE
Add a C++ program [word counter]

### ISSUE THREAD

**Issue by arpitbaheti2002** [ron2111/Hacktoberfest2021_awesome-projects#324]
### Description :
I want to add a **C++ program** in "**Hacktoberfest2021_awesome-projects/Unique C++ Projects/**" that counts the number of words in a sentence.

### Use :
This C++ program takes a sentence as input from the user and stores it in the form of a String.
Then counts the number of words in considering each word is separated by a blank space (" ").

### Concepts used:
- Strings
- Loop
- Basic input and output.

**Comment by ron2111** [comment]
Great description Arpit, but there is no need to raise an issue.
You can directly raise a PR and after going through the README.md file.

**Comment by arpitbaheti2002** [comment]
Thank you. I have opened a pull request for this program.
