### ISSUE TITLE
Add a C++ program that converts any string to its Binary form.

### ISSUE THREAD

**Issue by arpitbaheti2002** [ron2111/Hacktoberfest2021_awesome-projects#329]
### Description :
I want to add a **C++ program** in "**Hacktoberfest2021_awesome-projects/Unique C++ Projects/**" that converts any string to its Binary form.

### Function :
This C++ program takes a sentence as input from the user and stores it in the form of a String.
Then counts the number of words in considering each word is separated by a blank space (" ").

### Why is it AWESOME ? :
Being a beginner in programming I like learning by coding. So, I made this project to convert my and my friend's name in binary to know how the computer actually reads it.

### Concepts used:
- Strings
- Loop
- Basic input and output.
- ASCII.
- Binary number system.

**Comment by ron2111** [comment]
Just closed one of your issues like this. **Read its comment**
