### ISSUE TITLE
Add Web Dev Project #41

### ISSUE THREAD

**Issue by nishant-giri** [ron2111/Hacktoberfest2021_awesome-projects#73]
The PR Add Web Dev Project #41 hasn't been merged yet. Instead the updates done by me in README.md was merged before the project. Kindly look into this.

**Comment by ron2111** [comment]
Done, and do all the required changes regarding a single project in 1 PR only

**Comment by nishant-giri** [comment]
Thank you. Sure, I'll keep that in mind.
