### ISSUE TITLE
Add your amazing Web Development projects !!

### ISSUE THREAD

**Issue by ron2111** [ron2111/Hacktoberfest2021_awesome-projects#8]
Raise genuine PRs with your project and make sure to update the **project_doc**  available in the project folder with the name of your project and its description.

**Comment by Harshil-Jani** [comment]
Hey ! @ron2111 Can I add My Web Development Project that takes ScreenShot from the media device drivers and then place it on canvas element. It is built with simple HTML, CSS and Vanilla JS. Also, I can add few more features to existing model of mine.

**Comment by mondalraj** [comment]
I have added my Web Development project (pull request - #81 )
If you find this suitable please merge my pull request.

**Comment by ItsRoy69** [comment]
I have added my Web Development project 
If you find this suitable please merge my pull request.
