### ISSUE TITLE
Javascript framework/library based project

### ISSUE THREAD

**Issue by iamsunil25** [ron2111/Hacktoberfest2021_awesome-projects#91]
make a folder Javascript framework/library project
int his folder there will be many sub folder like
react-for react projects
angular-for angilar projects
vue-for vue.js projects

**Comment by iamsunil25** [comment]
@ron2111 i am working on this issue

**Comment by ron2111** [comment]
ok great @iamsunil25, sort out the projects as well and update the project_doc.md with instructions
